const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.EightDir,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Спрайт: 0},
	{ТайловыйФон: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{ТайловыйФон2: 0},
	{Текст: 0},
	{Кнопка: 0},
	{Кнопка2: 0},
	{ТайловыйФон3: 0},
	{Текст2: 0},
	{"8Направлений": 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{ТайловыйФон4: 0},
	{Текст3: 0},
	{Текст4: 0},
	{Кнопка3: 0},
	{Кнопка4: 0},
	{Аудио: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Текст: class extends self.ITextInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Текст3: class extends self.ITextInstance {},
	Текст4: class extends self.ITextInstance {},
	Кнопка3: class extends self.IButtonInstance {},
	Кнопка4: class extends self.IButtonInstance {},
	Аудио: class extends self.IInstance {}
}